/* eslint-disable no-unused-vars */
export enum QueryKeys {
  // loggedInUser
  GET_EVENT_INFO_BY_ID = 'GET_EVENT_INFO_BY_ID',
  GET_PAGINATED_LIKED_EVENTS_FOR_BUCKETLIST = 'GET_PAGINATED_LIKED_EVENTS_FOR_BUCKETLIST',
  GET_PAGINATED_USERS_WHO_LIKED_SAME_EVENT = 'GET_PAGINATED_USERS_WHO_LIKED_SAME_EVENT',
  GET_LOGGED_IN_USER_PROFILE = 'GET_LOGGED_IN_USER_PROFILE',
  GET_CURRENT_LOCATION_CITIES = 'GET_CURRENT_LOCATION_CITIES',

  // targetUser
  GET_TARGET_USER_INFO_PROFILE = 'GET_TARGET_USER_INFO_PROFILE',
  GET_PAGINATED_LIKED_EVENTS_FOR_BUCKETLIST_BY_TARGET_USER_ID = 'GET_PAGINATED_LIKED_EVENTS_FOR_BUCKETLIST_BY_TARGET_USER_ID',
  GET_PAGINATED_MATCHED_EVENTS_BY_TWO_USERS = 'GET_PAGINATED_MATCHED_EVENTS_BY_TWO_USERS',

  // friendships
  GET_FRIENDSHIP_BY_TARGET_USER_ID = 'GET_FRIENDSHIP_BY_TARGET_USER_ID',
  GET_PAGINATED_NEWEST_FRIENDS = 'GET_PAGINATED_NEWEST_FRIENDS',

  // search
  GET_HOME_TOWN_CITIES = 'GET_HOME_TOWN_CITIES',
  GET_ALL_LANGUAGES = 'GET_ALL_LANGUAGES',
  SEARCH_PAGINATED_FRIENDS_BY_USERNAME = 'SEARCH_PAGINATED_FRIENDS_BY_USERNAME',
  SEARCH_PAGINATED_USERS_BY_USERNAME = 'SEARCH_PAGINATED_USERS_BY_USERNAME',
  SEARCH_PAGINATED_EVENTS = 'SEARCH_PAGINATED_EVENTS',
}
