/* eslint-disable no-unused-vars */
export enum QueryKeys {
  GET_EVENTS,
  GET_LIKED_EVENTS,
  GET_EVENT_BY_ID,
  GET_MATCHED_EVENTS_BY_TWO_USERS,

  GET_USERS_WHO_LIKED_SAME_EVENT,
  GET_NEWEST_FRIENDS,
  GET_USER_INFO,
  GET_NEW_PEOPLE_INFO,
  GET_FRIENDSHIP_BY_RECEIVER_ID_AND_SENDER_ID,

  GET_CURRENT_LOCATION_CITIES,
  GET_HOME_TOWN_CITIES,

  GET_ALL_LANGUAGES,
}
