/* eslint-disable no-unused-vars */
export enum QueryKeys {
  // events
  GET_LATEST_EVENTS_WITH_PAGINATION,
  GET_LIKED_EVENTS_FOR_BUCKETLIST_WITH_PAGINATION,
  GET_EVENT_INFO_BY_ID,
  GET_MATCHED_EVENTS_BY_SAME_USERS_WITH_PAGINATION,

  // users
  GET_USERS_WHO_LIKED_SAME_EVENT_BY_ID_WITH_PAGINATION,
  GET_USER_INFO_PROFILE,
  GET_NEW_PEOPLE_INFO_PROFILE,
  GET_CURRENT_LOCATION_CITIES,
  GET_HOME_TOWN_CITIES,
  GET_ALL_LANGUAGES,

  // friendships
  GET_FRIENDSHIP_BY_RECEIVER_ID_AND_SENDER_ID,
  GET_NEWEST_FRIENDS_WITH_PAGINATION,
}
