// Generated by https://quicktype.io

export interface Cities {
  links: Link[];
  data: Datum[];
  metadata: Metadata;
}

export interface Datum {
  id: number;
  wikiDataId: string;
  type: string;
  name: string;
  country: string;
  countryCode: string;
  region: string;
  regionCode: string;
  regionWdId: string;
  latitude: number;
  longitude: number;
  population: number;
  distance: null | number;
  placeType: string;
}

// export enum Country {
//   Afghanistan = "Afghanistan",
// }

// export enum CountryCode {
//   AF = "AF",
// }

// export enum Type {
//   Adm2 = 'ADM2',
//   City = 'CITY',
// }

interface Link {
  rel: string;
  href: string;
}

interface Metadata {
  currentOffset: number;
  totalCount: number;
}
