// Generated by https://quicktype.io

export interface EventsListRes {
  events: Event[];
  totalEvents: number;
  currentPage: number;
  eventsPerPage: number;
}

export interface Event {
  id: number;
  createdAt: string;
  updatedAt: string;
  date: string;
  name: string;
  description: string;
  mediaUrl: string;
  mediaType: string;
  locationId: number;
  category: string;
  likes: object[];
  matches: object[];
}

export interface CreateEventRes {
  id: number;
  createdAt: string;
  updatedAt: string;
  date: string;
  name: string;
  description: string;
  mediaUrl: string;
  mediaType: string;
  locationId: number;
  category: string;
}
