
// LIKED EVENTS // Generated by https://quicktype.io

import { Like } from './Like';
import { Photo } from './User';

export interface LikedEventsListRes {
  events: Event[];
  totalEvents: number;
  currentPage: number;
  eventsPerPage: number;
}

export interface Event {
  id: number;
  createdAt: string;
  updatedAt: string;
  date: string;
  name: string;
  description: string;
  mediaUrl: string;
  mediaType: string;
  locationId: number;
  organizationId: number;
  category: string;
  matches: object[];
  likes: Like[];
}

export interface UserRes {
  id: number;
  avatar: string;
  photos: Photo[];
  username: string;
  email: string;
  phone: null;
  uid: string;
}
